from googlesearch import search
from pytube import Search
from deep_translator import GoogleTranslator
from better_profanity import profanity
import random
import time
import requests

profanity.load_censor_words()

def censor_and_check(text):
    # new text, False or True
    contains_bad_words = profanity.contains_profanity(text)
    censored_text = profanity.censor(text)
    return censored_text, contains_bad_words

def get_movie_details(movie_title):
    """
    Функция возвращает постер, название, описание и оценки фильма из OMDb API.
    """
    url = 'http://www.omdbapi.com/?i=tt3896198&apikey=3206f8fe' + f"&t={movie_title}"
    
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json()
        if data.get("Response") == "True":
            return {
                "Title": data.get("Title"),
                "Poster": data.get("Poster"),
                "Plot": data.get("Plot"),
                "Ratings": data.get("Ratings")
            }
        else:
            return {"error": data.get("Error")}
    else:
        return {"error": f"HTTP Error: {response.status_code}"}

def generate(prompt, style_preset, width, height):
    url_generate = "https://api.prodia.com/v1/sd/generate"
    url_status_template = "https://api.prodia.com/v1/job/{}"
    api_key = "8dca1ba1-d7d2-424f-b323-fcc34ad646b4"
    
    payload = {"prompt": prompt, "style_preset": style_preset, "width": width,
    "height": height}
    
    headers = {
        "accept": "application/json",
        "content-type": "application/json",
        "X-Prodia-Key": api_key
    }

    response1 = requests.post(url_generate, json=payload, headers=headers)
    if response1.status_code != 200:
        print(f"Error in request1: {response1.status_code}")
        print(response1.text)  # Print error details
        return None

    job_id = response1.json().get('job')
    if not job_id:
        print("No job ID received.")
        return None

    url_status = url_status_template.format(job_id)
    for _ in range(10):
        response2 = requests.get(url_status, headers=headers)
        if response2.status_code != 200:
            print(f"Error in request2: {response2.status_code}")
            print(response2.text)  
            return None

        data = response2.json()
        if data.get('status') == 'succeeded':
            return data.get('imageUrl')

        print("Job is still processing... ")
        time.sleep(1)

    print("Job did not complete within the expected time.")
    return None

async def get_random_video(query):
    search = Search(query)
    videos = search.results

    if not videos:
        return None

    return random.choice(videos)

def g(query):
    results = search(query, lang = 'en')
    
    link = next(results, None)
    return link

def github(str:str):
    return f"https://github.com/{str.replace(' ', '')}"

def trans(text, language):
    # auto
    translator = GoogleTranslator(source='auto', target=language)
    translated_text = translator.translate(text)
    
    return translated_text

def x(text):
    return f"https://x.com/{text.replace(' ', '')}"

def get_random_meme():
    url = 'https://meme-api.com/gimme'
    response = requests.get(url)
    data = response.json()
    meme_url = data['url']
    return meme_url

languages = {
    "English": "en",
    "Spanish": "es",
    "Chinese (Simplified)": "zh-CN",
    "Arabic": "ar",
    "Portuguese": "pt",
    "Russian": "ru",
    "Japanese": "ja",
    "German": "de",
    "French": "fr",
    "Italian": "it",
    "Korean": "ko",
    "Turkish": "tr",
    "Dutch": "nl",
    "Polish": "pl",
    "Ukrainian": "uk",
    "Greek" : "el"
}

language_choices = [f"{name} ({code})" for name, code in languages.items()]
##############


def brawlify_club(tag):
    tag = tag.replace('#', '') if '#' in tag else tag
    return f'https://brawlify.com/stats/club/{tag}'


jokes = [
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta.",
    "Why couldn't the bicycle stand up by itself? It was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "What do you call a bear with no teeth? A gummy bear.",
    "How do you organize a space party? You planet.",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you call a fish with no eyes? Fsh.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a cow with no legs? Ground beef.",
    "Why was the broom late? It swept in.",
    "Why don't fish play piano? Because you can't tuna fish.",
    "Why don't skeletons ever get in arguments? They don't have the guts.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "What do you call a dog magician? A labracadabrador.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
    "Why was the big cat disqualified from the race? Because it was a cheetah.",
    "Why don’t oysters share their pearls? Because they’re shellfish.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Why did the stadium get hot after the game? All of the fans left.",
    "Why can’t you give Elsa a balloon? Because she will let it go.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "Why can't you trust stairs? Because they're always up to something.",
    "What do you call fake noodles? An impasta.",
    "Why don't some fish play the piano? Because you can't tuna fish.",
    "Why are skeletons so calm? Because nothing gets under their skin.",
    "Why did the bicycle fall over? It was two-tired.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why don't scientists trust atoms? Because they make up everything.",
    "How do you fix a broken pumpkin? With a pumpkin patch.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "What do you get when you cross a snowman with a vampire? Frostbite.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a fish with no eyes? Fsh.",
    "How do you make a tissue dance? You put a little boogie in it.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the 'P' is silent.",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "Why don't some fish play piano? Because you can't tuna fish.",
    "Why did the stadium get hot after the game? All of the fans left.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why don’t some couples go to the gym? Because some relationships don't work out.",
    "Why can't you trust stairs? Because they're always up to something.",
    "What do you call fake noodles? An impasta.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "Why was the math book sad? It had too many problems.",
    "What do you call a pile of cats? A meowtain.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "Why don't fish play piano? Because you can't tuna fish.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Why was the big cat disqualified from the race? Because it was a cheetah.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "Why was the broom late? It swept in.",
    "What do you call a cow with no legs? Ground beef.",
    "Why did the stadium get hot after the game? All of the fans left.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why can't you trust stairs? Because they're always up to something.",
    "Why was the big cat disqualified from the race? Because it was a cheetah.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Why don't skeletons ever get in arguments? They don't have the guts.",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
    "Why was the broom late? It swept in.",
    "Why did the math book look sad? Because it had too many problems.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call fake noodles? An impasta.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "What do you call a fish with no eyes? Fsh.",
    "Why was the stadium so hot after the game? Because all the fans left.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "How do you organize a space party? You planet.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "What do you call a dog magician? A labracadabrador.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call fake spaghetti? An impasta.",
    "Why couldn't the bicycle stand up by itself? It was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese."
]

jokes.extend([
    "Why don't oysters share their pearls? Because they’re shellfish.",
    "Why did the picture go to jail? Because it was framed.",
    "Why did the coffee file a police report? It got mugged.",
    "Why don’t mountains get cold? They wear snow caps.",
    "Why did the belt go to jail? It held up a pair of pants.",
    "Why don’t teddy bears ever eat dessert? Because they’re always stuffed.",
    "Why do bicycles fall over? Because they’re two-tired.",
    "Why did the cookie go to the doctor? Because it felt crummy.",
    "Why do ghosts love elevators? Because they lift their spirits.",
    "Why did the fisherman put peanut butter into the sea? To go with the jellyfish.",
    "Why was the broom late? It swept in.",
    "What do you call a sleeping bull? A bulldozer.",
    "Why are frogs so happy? They eat whatever bugs them.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What’s a tornado’s favorite game? Twister.",
    "Why did the grape stop in the middle of the road? Because it ran out of juice.",
    "Why was the calendar always so tired? It had too many dates.",
    "What did one snowman say to the other? Do you smell carrots?",
    "Why did the ghost go to the party? To lift its spirits.",
    "What did the digital clock say to its mother? Look, Mom! No hands!",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "What do you call a group of musical fish? A bass band.",
    "Why can’t you give Elsa a balloon? Because she’ll let it go.",
    "What do you call a horse that lives next door? A neigh-bor.",
    "Why don’t cows play basketball? Because they’re afraid of the steaks.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "Why did the dog sit in the shade? Because it didn’t want to be a hot dog.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why was the skeleton afraid of the storm? He didn’t have the guts to face it.",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels."
])

teacher_jokes = [
    "Why did the teacher wear sunglasses? Because her students were so bright!",
    "What did the student say after his teacher explained multiplication? 'This is just a factor of life!'",
    "Why did the math book look sad? Because it had too many problems.",
    "How do you organize a space party? You planet!",
    "Why was the teacher cross-eyed? She couldn't control her pupils!",
    "What did the science book say to the math book? 'You have too many problems!'",
    "Why do teachers always carry a pencil? In case they have to draw a blank!",
    "What did one math teacher say to another? 'I have too many problems!'",
    "Why did the music teacher go to jail? Because she got caught with too many sharps!",
    "How does a teacher greet her class? 'Math-ter day, everyone!'",
    "Why did the student eat his homework? Because the teacher said it was a piece of cake!",
    "What’s a teacher’s favorite nation? Expla-nation!",
    "Why did the teacher get kicked out of the classroom? Because she kept talking about her ex-pupils!",
    "What do you call a teacher who never farts? A private tutor!",
    "Why was the math teacher so good at gardening? Because she knew how to plot!",
    "What do you get when you cross a teacher with a vampire? A person who can count to 10 without biting!",
    "Why was the computer cold? Because it left its Windows open!",
    "What did the teacher say to the student who was always daydreaming? 'You need to focus on the present!'",
    "How do teachers stay cool during summer? They have plenty of fans!",
    "Why did the teacher bring a ladder to school? To reach new heights!",
    "Why did the geography teacher break up with his girlfriend? Because she thought he was always on another continent!",
    "What do you call a teacher who loves math? A fraction of a teacher!",
    "Why are math teachers good at solving problems? Because they always find the solution!",
    "What do you call a math teacher who’s always late? A procrastin-ator!",
    "Why did the teacher give the student a globe? Because he needed a little perspective!",
    "What’s a teacher’s favorite dessert? A 'teaching' pie!",
    "Why did the teacher go to art school? To learn how to draw attention!",
    "What do you call a teacher who is always on time? A rarity!",
    "Why did the biology teacher break up with the chemistry teacher? There was no chemistry!",
    "What’s a teacher’s favorite type of music? 'Class'-ical!",
    "Why did the teacher bring string to school? To tie up loose ends!",
    "What did the teacher say when the class asked for extra credit? 'You can always count on me!'",
    "Why do teachers love nature? Because it has so many 'students'!",
    "What did the math teacher say at the beach? 'I’m here for some tan-gent!'",
    "How do you make a teacher smile? Tell them they’re the best!",
    "Why did the teacher go to the beach? To test the waters!",
    "What do teachers use to stay organized? A lesson plan!",
    "Why was the English teacher so good at gardening? Because she knew how to cultivate ideas!",
    "What did the teacher say when the student asked about homework? 'It’s in the syllabus!'",
    "Why did the teacher go to the bank? To get her 'interest' checked!",
    "What do you call a teacher with no classroom? A free spirit!",
    "Why did the teacher break up with the textbook? Because it was too boring!",
    "What do you call a teacher who loves history? A time traveler!",
    "Why did the teacher go on a diet? Because she wanted to reduce her class size!",
    "What did the teacher say to the class when it got quiet? 'Let’s make some noise!'",
    "Why was the gym teacher so successful? Because he knew how to motivate!",
    "What did the teacher say when asked about summer plans? 'I’m going to learn how to chill!'",
    "Why did the teacher stay after school? To get a little extra credit!",
    "What do you call a teacher who knows everything? A know-it-all!",
    "Why did the teacher love the library? Because it was full of stories!","What do teachers do when they are bored? They draw up lesson plans!",
    "Why was the physics teacher always calm? Because he had good 'momentum'!",
    "What do you call a teacher who can’t stop laughing? A pun-derful educator!",
    "Why did the teacher always carry a ruler? To measure success!",
    "What did the math teacher say to the student who was worried about tests? 'You’ve got this!'",
    "Why was the teacher so good at poker? Because she knew how to read the room!",
    "What did the teacher say to the class after a field trip? 'I hope you learned a lot!'",
    "Why did the teacher become a gardener? Because she wanted to grow knowledge!",
    "What do you call a teacher who loves science? A nerd with a passion!",
    "Why was the art teacher always broke? Because he spent all his money on supplies!",
    "What did the teacher say when the class got loud? 'Let’s keep it down, folks!'",
    "Why did the teacher get a promotion? Because she was outstanding in her field!",
    "What do you call a teacher who loves to travel? A globe-trotter!",
    "Why did the teacher bring a clock to class? To make every second count!",
    "What’s a teacher’s favorite game? 'Guess Who?'",
    "Why did the teacher take a pencil to bed? In case she had a 'brilliant idea'!",
    "What did the student say when asked about his homework? 'I put my heart into it!'",
    "Why was the music teacher so good at parties? Because she knew how to 'tune' in!",
    "What do you call a teacher who loves to read? A bookworm!",
    "Why did the teacher love math? Because it had so many solutions!",
    "What did the teacher say during the test? 'This is your moment to shine!'",
    "Why did the history teacher always carry a diary? To keep track of dates!",
    "What do you call a teacher who’s always in a hurry? A fast-tracker!",
    "Why did the teacher go to therapy? To work on her 'class' issues!",
    "What did the student say to the teacher who assigned too much homework? 'You’re a homework hoarder!'",
    "Why was the teacher so good at acting? Because she knew how to 'play' her role!",
    "What do you call a teacher who loves puzzles? A problem solver!",
    "Why did the teacher get a haircut? To have a fresh start for the new year!",
    "What did the teacher say when the class was quiet? 'I can hear crickets!'",
    "Why was the science teacher so popular? Because she had great experiments!",
    "What do you call a teacher who loves to joke? A pun-derful instructor!",
    "Why did the teacher go to the concert? To see her favorite band play!",
    "What do you call a teacher who loves to dance? A mover and a shaker!",
    "Why did the teacher join the gym? To work on her 'curriculum'!",
    "What did the teacher say when asked about her hobbies? 'I love to learn!'",
    "Why did the teacher stay late after school? To finish her grading!",
    "What do you call a teacher who loves technology? A tech-savvy educator!",
    "Why was the teacher excited for graduation? Because she saw her students succeed!",
    "What did the teacher say when students asked for advice? 'Always aim high!'",
    "Why did the teacher love cooking? Because she liked to mix things up!",
    "What do you call a teacher who loves outdoor activities? A nature enthusiast!",
    "Why did the teacher decorate her classroom? To create a positive environment!",
    "What did the teacher say to motivate her students? 'You can achieve anything!'",
    "Why was the teacher so organized? Because she had a plan for everything!",
    "What do you call a teacher who loves to explore? An adventurer!",
    "Why did the teacher give her students candy? To sweeten their learning experience!",
]


topics = [
    "adventure",
    "travel",
    "music",
    "gaming",
    "science",
    "technology",
    "sports",
    "cooking",
    "art",
    "history",
    "health",
    "education",
    "finance",
    "fashion",
    "lifestyle",
    "movies",
    "nature",
    "animals",
    "news",
    "photography",
    "fitness",
    "design",
    "psychology",
    "environment",
    "politics",
    "space",
    "architecture",
    "parenting",
    "automobiles",
    "literature",
    "comedy",
    "animation",
    "virtual reality",
    "music theory",
    "drone footage",
    "documentaries",
    "business",
    "marketing",
    "investing",
    "skincare",
    "haircare",
    "travel tips",
    "self-improvement",
    "motivation",
    "web development",
    "mobile apps",
    "e-sports",
    "outdoor activities",
    "DIY projects",
    "pets",
    "sustainable living",
    "data science",
    "artificial intelligence",
    "cryptocurrency",
    "hiking",
    "surfing",
    "fishing",
    "vlogging",
    "storytelling",
    "crafts",
    "home improvement",
    "cultural events",
    "social media",
    "public speaking",
    "historical events",
    "classic literature",
    "vintage cars",
    "urban exploration",
    "sci-fi",
    "fantasy",
    "mystery",
    "biographies",
    "travel vlogs",
    "spirituality",
    "yoga",
    "meditation",
    "classic music",
    "indie music",
    "hip hop",
    "pop culture",
    "baking",
    "sweets",
    "local cuisine",
    "street food",
    "comics",
    "anime",
    "technology reviews",
    "gadgets",
    "apps",
    "coding tutorials",
    "life hacks",
    "time management",
    "goal setting",
    "art tutorials",
    "calligraphy",
    "graphic novels",
    "virtual tours",
    "meme culture",
    "theater",
    "performance art",
    "experimental music",
    "classic films",
    "world history",
    "current events",
    "economic trends",
    "mental health",
    "team sports",
    "individual sports",
    "extreme sports",
    "water sports",
    "adventure travel",
    "wildlife",
    "cultural heritage",
    "fashion trends",
    "home decor",
    "celebrity news",
    "internet culture",
    "innovation",
    "sustainable fashion",
    "smart homes",
    "podcasts",
    "education technology",
    "cognitive science",
    "philosophy",
    "world religions",
    "ancient civilizations",
    "art movements",
    "social issues",
    "community service",
    "cloud computing",
    "cybersecurity",
    "machine learning",
    "software engineering",
    "blockchain",
    "DevOps",
    "networking",
    "database management",
    "agile methodologies",
    "open source",
    "personal finance",
    "digital art",
    "augmented reality",
    "historical fiction",
    "mythology",
    "marine biology",
    "urban gardening",
    "biohacking",
    "ethical hacking",
    "social entrepreneurship",
    "digital marketing",
    "food science",
    "eco-friendly products",
    "virtual events",
    "scientific research",
    "creative writing",
    "music production",
    "3D printing",
    "public art",
    "philanthropy",
    "cultural exchange",
    "international relations",
    "smart cities",
    "robotics",
    "nanotechnology",
    "alternative medicine",
    "life coaching",
    "bioengineering",
    "virtual assistants",
    "personal development",
    "non-profit organizations",
    "global issues",
    "language learning",
    "historical documentaries",
    "innovation in education",
    "cross-cultural communication",
    "Quantum computing",
    "Digital nomad lifestyle",
    "Augmented reality games",
    "User experience design", 
    "Ethical fashion",
    "Renewable energy",
    "Future of work",
    "Creative coding",
    "Genetic engineering",
    "Space exploration", 
    "Music therapy", 
    "Crossfit", 
    "Interactive storytelling",
    "Behavioral economics",
    "Marine conservation",
    "Urban planning", 
    "Disaster management", 
    "Cyberpsychology", 
    "Sustainable agriculture",
    "Food sustainability",
    "Personalized medicine", 
    "Mixed reality", 
    "Heritage conservation",
    "Crowd-sourced projects",
    "Mental wellness",
    "Experiential learning",
    "Social media influencers",
    "Digital privacy",
    "Community building",
    "Digital transformation"
]

topics_ru = [
    "приключения",
    "путешествия",
    "музыка",
    "игры",
    "наука",
    "технологии",
    "спорт",
    "кулинария",
    "искусство",
    "история",
    "здоровье",
    "образование",
    "финансы",
    "образ жизни",
    "фильмы",
    "природа",
    "животные",
    "новости",
    "фотография",
    "дизайн",
    "политика",
    "космос",
    "архитектура",
    "отношения",
    "родительство",
    "автомобили",
    "литература",
    "комедия",
    "анимация",
    "виртуальная реальность",
    "музыкальная теория",
    "дрон-съемка",
    "документальные фильмы",
    "бизнес",
    "маркетинг",
    "инвестирование",
    "уход за кожей",
    "уход за волосами",
    "советы по путешествиям",
    "самосовершенствование",
    "мотивация",
    "веб-разработка",
    "мобильные приложения",
    "киберспорт",
    "активный отдых",
    "DIY проекты",
    "домашние животные",
    "устойчивая жизнь",
    "наука о данных",
    "искусственный интеллект",
    "криптовалюта",
    "походы",
    "серфинг",
    "рыбалка",
    "влогинг",
    "рассказывание историй",
    "ремесла",
    "улучшение дома",
    "культурные события",
    "социальные медиа",
    "публичные выступления",
    "исторические события",
    "классическая литература",
    "ретро автомобили",
    "городская эксплорация",
    "научная фантастика",
    "фэнтези",
    "мистика",
    "биографии",
    "путешествия влогами",
    "духовность",
    "йога",
    "медитация",
    "классическая музыка",
    "инди музыка",
    "хип-хоп",
    "поп-культура",
    "выпечка",
    "сладости",
    "местная кухня",
    "уличная еда",
    "комиксы",
    "аниме",
    "обзоры технологий",
    "гаджеты",
    "приложения",
    "уроки программирования",
    "лайфхаки",
    "управление временем",
    "постановка целей",
    "уроки искусства",
    "каллиграфия",
    "графические романы",
    "виртуальные туры",
    "культура мемов",
    "театр",
    "перформанс-арт",
    "экспериментальная музыка",
    "классические фильмы",
    "мировая история",
    "актуальные события",
    "экономические тренды",
    "психическое здоровье",
    "командные виды спорта",
    "индивидуальные виды спорта",
    "экстремальные виды спорта",
    "водные виды спорта",
    "приключенческие путешествия",
    "дикие животные",
    "культурное наследие",
    "модные тренды",
    "декор дома",
    "новости о знаменитостях",
    "интернет-культура",
    "инновации",
    "устойчивая мода",
    "умные дома",
    "подкасты",
    "технологии образования",
    "когнитивная наука",
    "философия",
    "мировые религии",
    "древние цивилизации",
    "художественные движения",
    "социальные проблемы",
    "общественные инициативы",
    "облачные вычисления",
    "кибербезопасность",
    "машинное обучение",
    "программная инженерия",
    "блокчейн",
    "DevOps",
    "сетевая инфраструктура",
    "управление базами данных",
    "гибкие методологии",
    "открытое ПО",
    "личные финансы",
    "цифровое искусство",
    "дополненная реальность",
    "историческая фантастика",
    "мифология",
    "морская биология",
    "городское садоводство",
    "биохакинг",
    "этический хакинг",
    "социальное предпринимательство",
    "цифровой маркетинг",
    "наука о продуктах питания",
    "экологически чистые продукты",
    "виртуальные мероприятия",
    "научные исследования",
    "творческое письмо",
    "музыкальное производство",
    "3D-печать",
    "общественное искусство",
    "филантропия",
    "культурный обмен",
    "международные отношения",
    "умные города",
    "робототехника",
    "нанотехнологии",
    "альтернативная медицина",
    "лайф-коучинг",
    "биоинженерия",
    "виртуальные помощники",
    "личностное развитие",
    "некоммерческие организации",
    "глобальные проблемы",
    "изучение языка",
    "исторические документальные фильмы",
    "инновации в образовании",
    "межкультурная коммуникация",
    "Квантовые вычисления",
    "Цифровой кочевник",
    "Игры с дополненной реальностью",
    "Дизайн пользовательского опыта",
    "Этическая мода",
    "Возобновляемая энергетика",
    "Будущее работы",
    "Креативное программирование",
    "Генетическое инженерство",
    "Исследование космоса",
    "Музыкальная терапия",
    "Кроссфит",
    "Интерактивное повествование",
    "Поведенческая экономика",
    "Охрана морской среды",
    "Градостроительство",
    "Управление чрезвычайными ситуациями",
    "Киберпсихология",
    "Устойчивое сельское хозяйство",
    "Пищевая устойчивость",
    "Персонализированная медицина",
    "Смешанная реальность",
    "Сохранение культурного наследия",
    "Проекты с краудфандингом",
    "Психическое здоровье",
    "Экспериментальное обучение",
    "Влиятельные лица в социальных сетях",
    "Цифровая конфиденциальность",
    "Создание сообществ",
    "Цифровая трансформация"
]

topics_ua = [
    "пригоди",
    "подорожі",
    "музика",
    "ігри",
    "наука",
    "технології",
    "спорт",
    "готування",
    "мистецтво",
    "історія",
    "здоров'я",
    "освіта",
    "фінанси",
    "мода",
    "спосіб життя",
    "фільми",
    "природа",
    "тварини",
    "новини",
    "фотографія",
    "фітнес",
    "дизайн",
    "психологія",
    "навколишнє середовище",
    "політика",
    "космос",
    "архітектура",
    "виховання дітей",
    "автомобілі",
    "література",
    "комедія",
    "анімація",
    "доповнена реальність",
    "теорія музики",
    "відео з дронів",
    "документальні фільми",
    "бізнес",
    "маркетинг",
    "інвестування",
    "догляд за шкірою",
    "догляд за волоссям",
    "поради для подорожей",
    "особистісний розвиток",
    "мотивація",
    "веб-розробка",
    "мобільні додатки",
    "кіберспорт",
    "активний відпочинок",
    "DIY проекти",
    "домашні тварини",
    "стійкий спосіб життя",
    "наука про дані",
    "штучний інтелект",
    "криптовалюта",
    "похід",
    "серфінг",
    "рибалка",
    "влогінг",
    "оповідання",
    "рукоділля",
    "поліпшення дому",
    "культурні події",
    "соціальні мережі",
    "публічні виступи",
    "історичні події",
    "класична література",
    "вінтажні автомобілі",
    "урбаністичні дослідження",
    "наукова фантастика",
    "фентезі",
    "містика",
    "біографії",
    "влоги про подорожі",
    "духовність",
    "йога",
    "медитація",
    "класична музика",
    "інді-музика",
    "хіп-хоп",
    "поп-культура",
    "випічка",
    "солодощі",
    "місцева кухня",
    "вулична їжа",
    "комікси",
    "аніме",
    "огляди технологій",
    "гаджети",
    "додатки",
    "уроки кодування",
    "життєві хаки",
    "управління часом",
    "встановлення цілей",
    "уроки мистецтва",
    "калліграфія",
    "графічні романи",
    "віртуальні тури",
    "культура мемів",
    "театр",
    "перформанс-арт",
    "експериментальна музика",
    "класичні фільми",
    "світова історія",
    "поточні події",
    "економічні тенденції",
    "ментальне здоров'я",
    "командні види спорту",
    "індивідуальні види спорту",
    "екстремальні види спорту",
    "водні види спорту",
    "пригодницькі подорожі",
    "дикі тварини",
    "культурна спадщина",
    "тренди моди",
    "декор дому",
    "новини знаменитостей",
    "культура інтернету",
    "інновації",
    "стійка мода",
    "розумні будинки",
    "подкасти",
    "технології в освіті",
    "когнітивні науки",
    "філософія",
    "світові релігії",
    "стародавні цивілізації",
    "рухи мистецтв",
    "соціальні проблеми",
    "громадська діяльність",
    "хмарні обчислення",
    "кібербезпека",
    "машинне навчання",
    "програмна інженерія",
    "блокчейн",
    "DevOps",
    "мережеві технології",
    "управління базами даних",
    "гнучкі методології",
    "відкритий код",
    "особисті фінанси",
    "цифрове мистецтво",
    "доповнена реальність",
    "історичний роман",
    "міфологія",
    "морська біологія",
    "урбаністичне садівництво",
    "біохакінг",
    "етичний хакінг",
    "соціальне підприємництво",
    "цифровий маркетинг",
    "наука про їжу",
    "екологічні продукти",
    "віртуальні події",
    "наукові дослідження",
    "творче письмо",
    "музичне виробництво",
    "3D-друк",
    "публічне мистецтво",
    "філантропія",
    "культурний обмін",
    "міжнародні відносини",
    "розумні міста",
    "робототехніка",
    "нанотехнології",
    "альтернативна медицина",
    "життєвий коучинг",
    "біоінженерія",
    "віртуальні помічники",
    "особистісний розвиток",
    "недержавні організації",
    "глобальні проблеми",
    "вивчення мов",
    "історичні документальні фільми",
    "інновації в освіті",
    "міжкультурна комунікація",
    "Квантові обчислення",
    "Цифровий кочівник",
    "Ігри з доповненою реальністю",
    "Дизайн користувацького досвіду",
    "Етична мода",
    "Відновлювальна енергетика",
    "Майбутнє роботи",
    "Креативне програмування",
    "Генетичне інженерство",
    "Дослідження космосу",
    "Музична терапія","Кросфіт",
    "Інтерактивне оповідання",
    "Поведінкова економіка",
    "Охорона морського середовища",
    "Міське планування",
    "Управління катастрофами",
    "Кіберпсихологія",
    "Стійке сільське господарство",
    "Пищева стійкість",
    "Персоналізована медицина",
    "Змішана реальність",
    "Сохранение культурного наследия",
    "Проекти з краудфандингом",
    "Ментальне благополуччя",
    "Експериментальне навчання",
    "Влиятельні особи в соціальних мережах",
    "Цифрова конфіденційність",
    "Будування спільноти",
    "Цифрова трансформація"
]

topics_es = [
    "aventura",
    "viajes",
    "música",
    "juegos",
    "ciencia",
    "tecnología",
    "deportes",
    "cocina",
    "arte",
    "historia",
    "salud",
    "educación",
    "finanzas",
    "moda",
    "estilo de vida",
    "películas",
    "naturaleza",
    "animales",
    "noticias",
    "fotografía",
    "fitness",
    "diseño",
    "psicología",
    "medio ambiente",
    "política",
    "espacio",
    "arquitectura",
    "paternidad",
    "automóviles",
    "literatura",
    "comedia",
    "animación",
    "realidad aumentada",
    "teoría musical",
    "imágenes de drones",
    "documentales",
    "negocios",
    "marketing",
    "inversión",
    "cuidado de la piel",
    "cuidado del cabello",
    "consejos de viaje",
    "autoayuda",
    "motivación",
    "desarrollo web",
    "aplicaciones móviles",
    "e-sports",
    "actividades al aire libre",
    "proyectos DIY",
    "mascotas",
    "vida sostenible",
    "ciencia de datos",
    "inteligencia artificial",
    "criptomoneda",
    "senderismo",
    "surf",
    "pesca",
    "vlogging",
    "narrativa",
    "manualidades",
    "mejora del hogar",
    "eventos culturales",
    "redes sociales",
    "oratoria",
    "eventos históricos",
    "literatura clásica",
    "autos vintage",
    "exploración urbana",
    "ciencia ficción",
    "fantasía",
    "misterio",
    "biografías",
    "vlogs de viaje",
    "espiritualidad",
    "yoga",
    "meditación",
    "música clásica",
    "música indie",
    "hip hop",
    "cultura pop",
    "pastelería",
    "dulces",
    "cocina local",
    "comida callejera",
    "cómics",
    "anime",
    "reseñas tecnológicas",
    "gadgets",
    "aplicaciones",
    "tutoriales de codificación",
    "trucos de vida",
    "gestión del tiempo",
    "establecimiento de metas",
    "tutoriales de arte",
    "caligrafía",
    "novelas gráficas",
    "tours virtuales",
    "cultura de memes",
    "teatro",
    "arte performático",
    "música experimental",
    "películas clásicas",
    "historia mundial",
    "eventos actuales",
    "tendencias económicas",
    "salud mental",
    "deportes en equipo",
    "deportes individuales",
    "deportes extremos",
    "deportes acuáticos",
    "viajes de aventura",
    "vida salvaje",
    "patrimonio cultural",
    "tendencias de moda",
    "decoración del hogar",
    "noticias de celebridades",
    "cultura de internet",
    "innovación",
    "moda sostenible",
    "hogares inteligentes",
    "podcasts",
    "tecnología educativa",
    "ciencias cognitivas",
    "filosofía",
    "religiones del mundo",
    "civilizaciones antiguas",
    "movimientos artísticos",
    "problemas sociales",
    "servicio comunitario",
    "computación en la nube",
    "ciberseguridad",
    "aprendizaje automático",
    "ingeniería de software",
    "blockchain",
    "DevOps",
    "redes",
    "gestión de bases de datos",
    "metodologías ágiles",
    "código abierto",
    "finanzas personales",
    "arte digital",
    "realidad aumentada",
    "ficción histórica",
    "mitología",
    "biología marina",
    "jardinería urbana",
    "biohacking",
    "hacking ético",
    "emprendimiento social",
    "marketing digital",
    "ciencia alimentaria",
    "productos ecológicos",
    "eventos virtuales",
    "investigación científica",
    "escritura creativa",
    "producción musical",
    "impresión 3D",
    "arte público",
    "filantropía",
    "intercambio cultural",
    "relaciones internacionales",
    "ciudades inteligentes",
    "robótica",
    "nanotecnología",
    "medicina alternativa",
    "coaching de vida",
    "bioingeniería",
    "asistentes virtuales",
    "desarrollo personal",
    "organizaciones sin fines de lucro",
    "problemas globales",
    "aprendizaje de idiomas",
    "documentales históricos",
    "innovación en educación",
    "comunicación intercultural",
    "Computación cuántica",
    "Estilo de vida nómada digital",
    "Juegos de realidad aumentada",
    "Diseño de experiencia de usuario",
    "Moda ética",
    "Energía renovable",
    "Futuro del trabajo","Codificación creativa",
    "Ingeniería genética",
    "Exploración espacial",
    "Terapia musical",
    "Crossfit",
    "Narrativa interactiva",
    "Economía del comportamiento",
    "Conservación marina",
    "Planificación urbana",
    "Gestión de desastres",
    "Ciberpsicología",
    "Agricultura sostenible",
    "Sostenibilidad alimentaria",
    "Medicina personalizada",
    "Realidad mixta",
    "Conservación del patrimonio",
    "Proyectos de financiación colectiva",
    "Bienestar mental",
    "Aprendizaje experiencial",
    "Influencers en redes sociales",
    "Privacidad digital",
    "Construcción de comunidades",
    "Transformación digital"
]

topics_de = [
    "Abenteuer",
    "Reisen",
    "Musik",
    "Gaming",
    "Wissenschaft",
    "Technologie",
    "Sport",
    "Kochen",
    "Kunst",
    "Geschichte",
    "Gesundheit",
    "Bildung",
    "Finanzen",
    "Mode",
    "Lebensstil",
    "Filme",
    "Natur",
    "Tiere",
    "Nachrichten",
    "Fotografie",
    "Fitness",
    "Design",
    "Psychologie",
    "Umwelt",
    "Politik",
    "Weltraum",
    "Architektur",
    "Elternschaft",
    "Autos",
    "Literatur",
    "Komödie",
    "Animation",
    "Virtuelle Realität",
    "Musiktheorie",
    "Drohnenaufnahmen",
    "Dokumentarfilme",
    "Geschäft",
    "Marketing",
    "Investieren",
    "Hautpflege",
    "Haarpflege",
    "Reisetipps",
    "Selbstverbesserung",
    "Motivation",
    "Webentwicklung",
    "Mobile Apps",
    "E-Sport",
    "Outdoor-Aktivitäten",
    "DIY-Projekte",
    "Haustiere",
    "Nachhaltiges Leben",
    "Datenwissenschaft",
    "Künstliche Intelligenz",
    "Kryptowährung",
    "Wandern",
    "Surfen",
    "Angeln",
    "Vlogging",
    "Geschichten erzählen",
    "Handwerk",
    "Heimwerken",
    "Kulturelle Ereignisse",
    "Soziale Medien",
    "Öffentliches Sprechen",
    "Historische Ereignisse",
    "Klassische Literatur",
    "Oldtimer",
    "Städtische Erkundung",
    "Sci-Fi",
    "Fantasy",
    "Mystery",
    "Biografien",
    "Reise-Vlogs",
    "Spiritualität",
    "Yoga",
    "Meditation",
    "Klassische Musik",
    "Indie-Musik",
    "Hip-Hop",
    "Popkultur",
    "Backen",
    "Süßigkeiten",
    "Lokale Küche",
    "Straßenessen",
    "Comics",
    "Anime",
    "Technologiebewertungen",
    "Gadgets",
    "Apps",
    "Coding-Tutorials",
    "Life-Hacks",
    "Zeitmanagement",
    "Zielsetzung",
    "Kunst-Tutorials",
    "Kalligrafie",
    "Grafikromane",
    "Virtuelle Touren",
    "Meme-Kultur",
    "Theater",
    "Performance-Kunst",
    "Experimentelle Musik",
    "Klassische Filme",
    "Weltgeschichte",
    "Aktuelle Ereignisse",
    "Wirtschaftstrends",
    "Mentale Gesundheit",
    "Teamsport",
    "Einzelsport",
    "Extremsport",
    "Wassersport",
    "Abenteuerreisen",
    "Wildtiere",
    "Kulturelles Erbe",
    "Modetrends",
    "Inneneinrichtung",
    "Promi-Nachrichten",
    "Internetkultur",
    "Innovation",
    "Nachhaltige Mode",
    "Smart Homes",
    "Podcasts",
    "Bildungstechnologie",
    "Kognitionswissenschaft",
    "Philosophie",
    "Weltreligionen",
    "Antike Zivilisationen",
    "Kunstbewegungen",
    "Soziale Themen",
    "Gemeinschaftsdienst",
    "Cloud Computing",
    "Cybersicherheit",
    "Maschinelles Lernen",
    "Software-Engineering",
    "Blockchain",
    "DevOps",
    "Netzwerke",
    "Datenbankmanagement",
    "Agile Methoden",
    "Open Source",
    "Persönliche Finanzen",
    "Digitale Kunst",
    "Erweiterte Realität",
    "Historische Fiktion",
    "Mythologie",
    "Meeresbiologie",
    "Städtisches Gärtnern",
    "Biohacking",
    "Ethisches Hacking",
    "Soziales Unternehmertum",
    "Digitales Marketing",
    "Lebensmittelwissenschaft",
    "Ökofreundliche Produkte",
    "Virtuelle Ereignisse",
    "Wissenschaftliche Forschung",
    "Kreatives Schreiben",
    "Musikproduktion",
    "3D-Druck",
    "Öffentliche Kunst",
    "Philanthropie",
    "Kulturaustausch",
    "Internationale Beziehungen",
    "Smart Cities",
    "Robotik",
    "Nanotechnologie",
    "Alternative Medizin",
    "Life Coaching",
    "Bioengineering",
    "Virtuelle Assistenten",
    "Persönliche Entwicklung",
    "Non-Profit-Organisationen",
    "Globale Themen",
    "Sprachen lernen",
    "Historische Dokumentationen",
    "Innovation in der Bildung",
    "Interkulturelle Kommunikation",
    "Quantencomputing",
    "Digitaler Nomaden-Lifestyle",
    "Augmented Reality-Spiele",
    "Benutzererfahrung Design",
    "Ethische Mode",
    "Erneuerbare Energien",
    "Zukunft der Arbeit",
    "Kreatives Programmieren",
    "Gentechnik",
    "Raumfahrt",
    "Musiktherapie",
    "Crossfit",
    "Interaktives Erzählen",
    "Verhaltensökonomie",
    "Meeresschutz",
    "Stadtplanung",
    "Katastrophenmanagement",
    "Cyberpsychologie",
    "Nachhaltige Landwirtschaft",
    "Lebensmittel-Nachhaltigkeit",
    "Personalisierte Medizin",
    "Gemischte Realität",
    "Denkmalschutz",
    "Crowd-Source-Projekte",
    "Mentales Wohlbefinden",
    "Erfahrungslernen",
    "Social Media Influencer",
    "Digitaler Datenschutz",
    "Gemeinschaftsaufbau",
    "Digitale Transformation"
]

topic_zh = [
    "冒险",
    "旅行",
    "音乐",
    "游戏",
    "科学",
    "技术",
    "体育",
    "烹饪",
    "艺术",
    "历史",
    "健康",
    "教育",
    "金融",
    "时尚",
    "生活方式",
    "电影",
    "自然",
    "动物",
    "新闻",
    "摄影",
    "健身",
    "设计",
    "心理学",
    "环境",
    "政治",
    "太空",
    "建筑",
    "育儿",
    "汽车",
    "文学",
    "喜剧",
    "动画",
    "虚拟现实",
    "音乐理论",
    "无人机视频",
    "纪录片",
    "商业",
    "市场营销",
    "投资",
    "护肤",
    "护发",
    "旅行提示",
    "自我提升",
    "激励",
    "网页开发",
    "移动应用",
    "电子竞技",
    "户外活动",
    "DIY项目",
    "宠物",
    "可持续生活",
    "数据科学",
    "人工智能",
    "加密货币",
    "徒步旅行",
    "冲浪",
    "钓鱼",
    "视频博客",
    "故事讲述",
    "手工艺",
    "家居改进",
    "文化活动",
    "社交媒体",
    "公众演讲",
    "历史事件",
    "经典文学",
    "老爷车",
    "城市探险",
    "科幻",
    "奇幻",
    "悬疑",
    "传记",
    "旅行视频博客",
    "灵性",
    "瑜伽",
    "冥想",
    "古典音乐",
    "独立音乐",
    "嘻哈",
    "流行文化",
    "烘焙",
    "甜点",
    "当地美食",
    "街头食品",
    "漫画",
    "动漫",
    "技术评测",
    "小工具",
    "应用程序",
    "编程教程",
    "生活窍门",
    "时间管理",
    "目标设定",
    "艺术教程",
    "书法",
    "图画小说",
    "虚拟导览",
    "表情包文化",
    "戏剧",
    "表演艺术",
    "实验音乐",
    "经典电影",
    "世界历史",
    "时事",
    "经济趋势",
    "心理健康",
    "团体运动",
    "个人运动",
    "极限运动",
    "水上运动",
    "冒险旅行",
    "野生动物",
    "文化遗产",
    "时尚趋势",
    "家居装饰",
    "名人新闻",
    "网络文化",
    "创新",
    "可持续时尚",
    "智能家居",
    "播客",
    "教育技术",
    "认知科学",
    "哲学",
    "世界宗教",
    "古代文明",
    "艺术运动",
    "社会问题",
    "社区服务",
    "云计算",
    "网络安全",
    "机器学习",
    "软件工程",
    "区块链",
    "DevOps",
    "网络",
    "数据库管理",
    "敏捷方法",
    "开源",
    "个人理财",
    "数字艺术",
    "增强现实",
    "历史小说",
    "神话",
    "海洋生物学",
    "城市园艺",
    "生物黑客",
    "道德黑客",
    "社会创业",
    "数字营销",
    "食品科学",
    "环保产品",
    "虚拟事件",
    "科学研究",
    "创意写作",
    "音乐制作",
    "3D打印",
    "公共艺术",
    "慈善事业",
    "文化交流",
    "国际关系",
    "智慧城市",
    "机器人",
    "纳米技术",
    "替代医学",
    "生活教练",
    "生物工程",
    "虚拟助理",
    "个人发展",
    "非营利组织",
    "全球问题",
    "语言学习",
    "历史纪录片",
    "教育创新",
    "跨文化交流",
    "量子计算",
    "数字游民生活方式",
    "增强现实游戏",
    "用户体验设计",
    "道德时尚",
    "可再生能源",
    "未来的工作",
    "创意编程",
    "基因工程",
    "太空探索",
    "音乐疗法",
    "CrossFit",
    "互动叙事",
    "行为经济学",
    "海洋保护",
    "城市规划",
    "灾害管理",
    "网络心理学",
    "可持续农业",
    "食品可持续性",
    "个性化医疗",
    "混合现实",
    "遗产保护",
    "众包项目",
    "心理健康",
    "体验式学习",
    "社交媒体影响者",
    "数字隐私",
    "社区建设",
    "数字化转型"
]
